### ISSUE TITLE
Downloaded only 1 episode of total 6 episodes in a series.

### ISSUE THREAD

**Issue by ghost** [carlosflorencio/laracasts-downloader#82]
For some reason, it is not downloading all the episodes if a specific series.
Seems like other series have no issue, but the series i want to download, it is not downloading that series.

Only downloads the the first part, but does not download the remaining series.

Right now, in this series are total of 6 episodes, it downloaded only 1 and not detected other episodes.

![image](https://user-images.githubusercontent.com/26646476/55155349-f16eb300-5178-11e9-964b-51bd657dd9ab.png)

Here is the directory in my system

![image](https://user-images.githubusercontent.com/26646476/55155383-0e0aeb00-5179-11e9-97ee-6953496533af.png)

Laracast has total of 6 episodes at the moment on site.
![image](https://user-images.githubusercontent.com/26646476/55155560-840f5200-5179-11e9-95ba-c1aae3b21f32.png)

I tried again and again. deleting the directory and also tried deleting the first video, restarting the Command Prompt CMD, But no success so far.

**Comment by carlosflorencio** [comment]
Hi,

Do you have any `.skip` files? 
Can you debug the script and see what's going on? 

I don't have the time right now to investigate this.

Thanks

**Comment by ghost** [comment]
> Hi,
> 
> Do you have any `.skip` files?
> Can you debug the script and see what's going on?
> 
> I don't have the time right now to investigate this.
> 
> Thanks

No, i do not have any .skip file in the directory.
i even deleted directory back again and started the process back again.
I also even started CMD as an administrator. Tried multiple times. but no success.
So had to manually download all files one by one from the laracast manually :(

**Comment by Lambik** [comment]
Hi,

I tried this course as well, and found that it's not this script's fault, nor is it algolia. The algolia API returns (both on the real site, and in this script) that "episode_count: 1" even though it's 6 (or 7 as of right now). Therefore the downloader script only loops for that 1 episode, to download it.

My guess is that laracasts isn't updating their algolia index as they once did? Because the next series, "What's New in Laravel 5.8", also has 5 real episodes, but algolia returns "episode_count: 4".

**Comment by carlosflorencio** [comment]
Should be fixed by https://github.com/carlosflorencio/laracasts-downloader/pull/84
